#!/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/python
import os
import sys
import fileinput


def main(f):
    '''update all github repos'''
    
    



if __name__ == '__main__':
    main()


"""


# This is where I want my script to start.
cd ~/github/

# Let the person running the script know what's going on.
echo -e "\n\033[1mPulling in latest changes for all repositories...\033[0m\n"

# Find all directories here - that are at least 1 level down, but don't go any further than 1 directory.
# Go into those directories and pull the repository.
for i in $(find . -maxdepth 1 -mindepth 1 -type d); do
  echo -e "\033[1m"+$i+"\033[0m"; cd $i; git remote -v; git pull;
  cd ~/github/
done

echo -e "\n\033[1mComplete! Do work son!\033[0m\n"

"""